In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\HP\Downloads\data12-cleaned.csv")

In [3]:
df.shape

(1237, 9)

In [4]:
#Shows(rows,columns)

In [5]:
df.head()

,Order ID,Customer ID,Order Date,Postal Code,Sales,Product ID,Quantity,Discount,Profit
0,CA-2015-106320,EB-13870,12-Oct-22,84057,1044.63,FUR-TA-10000577,3,0.0,240.2649
1,CA-2016-169194,LH-16900,20-Jun-16,19901,45.00,TEC-AC-10002167,3,0.0,4.9500
2,CA-2017-114440,TB-21520,14-Sep-17,49201,19.05,OFF-PA-10004675,3,0.0,8.7630
3,CA-2016-109806,JS-15685,17-Sep-16,90036,20.10,OFF-AR-10004930,3,0.0,6.6330
4,CA-2015-110457,DK-13090,03-Feb-15,98103,787.53,FUR-TA-10001768,3,0.0,165.3813

In [6]:
#Shows first 5 rows of dataset

In [7]:
df.tail()

,Order ID,Customer ID,Order Date,Postal Code,Sales,Product ID,Quantity,Discount,Profit
1232,CA-2017-141705,PO-18850,24-Oct-17,76063,517.405,FUR-TA-10004607,5,0.3,-81.3065
1233,CA-2014-116666,KT-16480,05-Aug-14,19134,1799.970,TEC-CO-10001449,5,0.4,239.9960
1234,CA-2016-150483,BP-11290,31-May-16,62521,32.064,FUR-FU-10001379,3,0.6,-12.8256
1235,CA-2017-111717,SW-20245,10-Oct-17,60505,239.358,FUR-CH-10001545,3,0.3,-47.8716
1236,CA-2015-116638,JH-15985,28-Jan-15,28027,4297.644,FUR-TA-10000198,13,0.4,-1862.3124

In [8]:
#Shows last 5 rows of dataset

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1237 entries, 0 to 1236
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order ID     1237 non-null   object
 1   Customer ID  1237 non-null   object
 2   Order Date   1237 non-null   object
 3   Postal Code  1237 non-null   int64
 4   Sales        1237 non-null   float64
 5   Product ID   1237 non-null   object
 6   Quantity     1237 non-null   int64
 7   Discount     1237 non-null   float64
 8   Profit       1237 non-null   float64
dtypes: float64(3), int64(2), object(4)
memory usage: 87.1+ KB

In [10]:
#Shows column names,data types,and missing values

In [11]:
df.describe()

        Postal Code         Sales     Quantity     Discount       Profit
count   1237.000000   1237.000000  1237.000000  1237.000000  1237.000000
mean   55725.782538    220.834940     3.723525     0.157065    18.761712
std    31499.347215    570.581128     2.196910     0.207244   209.863486
min     1453.000000      1.080000     1.000000     0.000000 -3839.990400
25%    28027.000000     17.456000     2.000000     0.000000     1.764000
50%    59102.000000     55.176000     3.000000     0.200000     8.326800
75%    90004.000000    199.980000     5.000000     0.200000    26.376000
max    99207.000000  11199.968000    14.000000     0.800000  3919.988800

In [12]:
#Shows statistical summary(mean,min.max,etc)

In [14]:
df.shape[0]

1237

In [15]:
#How many rows

In [16]:
df.shape[1]

9

In [17]:
#How many columns

In [18]:
df.isnull().sum()

Order ID       0
Customer ID    0
Order Date     0
Postal Code    0
Sales          0
Product ID     0
Quantity       0
Discount       0
Profit         0
dtype: int64

In [19]:
#Which columns have missing value

In [22]:
a=df["Profit"].mean()
print(a)

18.761712206952303

In [23]:
#What is the average value of one numeric column